In [1]:
!pip install yfinance

Collecting yfinance
  Downloading yfinance-0.1.70-py2.py3-none-any.whl (26 kB)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.3.5)
Collecting lxml>=4.5.1
  Downloading lxml-4.8.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (6.4 MB)
     |████████████████████████████████| 6.4 MB 6.6 MB/s
Collecting requests>=2.26
  Downloading requests-2.27.1-py2.py3-none-any.whl (63 kB)
     |████████████████████████████████| 63 kB 1.3 MB/s
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.7/dist-packages (from yfinance) (0.0.10)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.21.6)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24.0->yfinance) (1.15.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (1.24.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.10)
Installing collected packages: requests, lxml, yfinance
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0
  Attempting uninstall: lxml
    Found existing installation: lxml 4.2.6
    Uninstalling lxml-4.2.6:
      Successfully uninstalled lxml-4.2.6
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.27.1 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
Successfully installed lxml-4.8.0 requests-2.27.1 yfinance-0.1.70

In [8]:
stock_symbol = "RELIANCE.NS"
period = "60d"
interval = "15m"

In [9]:
import yfinance as yf
from datetime import datetime
import pandas as pd

data = yf.download(tickers=stock_symbol, 
                    period=period, 
                    interval=interval,
                    auto_adjust = True)

[*********************100%***********************]  1 of 1 completed

In [10]:
# add time column
time_column = []
for i in data.index:
    time_column.append(i.to_pydatetime())

data = data.assign(time=pd.Series(time_column).values)

In [11]:
data.reset_index(inplace=True)

# rename columns according to our older convention
data.rename(
    { 'Open': 'open',
    'High': 'high',
    'Low' : 'low',
    'Close':'close',
    'Volume' : 'volume'},
    axis=1,
    inplace=True)

In [12]:
# drop rows where volume traded==0 it only happens during start of day 
# so is probably not needed
drop_rows = []
for i in range(len(data)):
    # print(type(data["volume"][i]))
    if data["volume"][i]==0 :
        drop_rows.append(i)

data.drop(data.index[drop_rows], inplace=True)

In [13]:
data.drop(['Datetime'], axis=1, inplace=True)
data

,open,high,low,close,volume,time
0,2365.000000,2372.300049,2355.500000,2357.500000,255576,2022-01-28 03:45:00
1,2357.500000,2363.899902,2350.000000,2358.600098,338141,2022-01-28 04:00:00
2,2358.399902,2365.800049,2355.000000,2360.949951,257218,2022-01-28 04:15:00
3,2360.350098,2361.699951,2350.050049,2352.000000,212922,2022-01-28 04:30:00
4,2352.850098,2354.149902,2342.399902,2352.199951,263049,2022-01-28 04:45:00
...,...,...,...,...,...,...
1482,2811.399902,2812.500000,2805.000000,2809.949951,304172,2022-04-27 05:30:00
1483,2809.800049,2810.000000,2800.100098,2801.000000,240899,2022-04-27 05:45:00
1484,2801.600098,2805.649902,2798.850098,2800.399902,212906,2022-04-27 06:00:00
1485,2800.550049,2810.000000,2798.050049,2806.500000,187436,2022-04-27 06:15:00
1486,2806.500000,2814.000000,2805.399902,2811.199951,116566,2022-04-27 06:30:00

In [14]:
data.to_csv(f"./{stock_symbol}_{period}_{interval}.csv")
data.isnull().sum()

open      0
high      0
low       0
close     0
volume    0
time      0
dtype: int64